DISEASE_INFO = {

"Normal Beat":{
"Risk":"Low",
"Description":"Normal ECG rhythm detected.",
"Recommendation":"No abnormality detected. Maintain a healthy lifestyle."
},

"Left Bundle Branch Block":{
"Risk":"Medium",
"Description":"Delay in electrical conduction through the left ventricle.",
"Recommendation":"Consult a cardiologist."
},

"Right Bundle Branch Block":{
"Risk":"Medium",
"Description":"Electrical conduction delay in the right ventricle.",
"Recommendation":"Medical evaluation recommended."
},

"Atrial Premature Beat":{
"Risk":"Medium",
"Description":"Premature heartbeat originating from the atria.",
"Recommendation":"Reduce stress and consult a doctor if frequent."
},

"Premature Ventricular Contraction":{
"Risk":"High",
"Description":"Extra heartbeat originating from ventricles.",
"Recommendation":"Immediate cardiac evaluation recommended."
},

"Fusion Beat":{
"Risk":"High",
"Description":"Fusion of normal and ventricular beats.",
"Recommendation":"Consult a cardiologist immediately."
},

"Paced Beat":{
"Risk":"Low",
"Description":"Heartbeat generated by pacemaker.",
"Recommendation":"Routine pacemaker follow-up."
}

}